#!/bin/bash

# Update pip package
pip install --upgrade pip

# Install GDAL specific version
# for compatibility with last GDAL
# installation
cd /opt && pip download GDAL==2.2.1
tar -xvzf GDAL-2.2.1.tar.gz > /dev/null 2>&1
cd GDAL-2.2.1
python setup.py build_ext --include-dirs=/usr/include/gdal/ > /dev/null 2>&1
python setup.py install
cd /opt && rm -rf GDAL-2.2.1

# Install python dependencies
cd /opt/worker
python setup.py develop

# Run Worker
./geo_worker_run/worker.sh

sleep 20
