# Declare base image, because this software needs
# the latest rabbitmq docker built image with all
# the necessary to run properly.

FROM rabbitmq:alpine
MAINTAINER Alejandro F. Carrera

VOLUME ["/data/log", "/data/mnesia"]
